### ISSUE TITLE
Support PhantomJS - Feature request

### ISSUE THREAD

**Issue by landau** [wookiehangover/grunt-mocha-selenium#1]
This plugin looks quite nice, but I'd like to be able to run my tests in PhantomJS env as well.

https://npmjs.org/package/grunt-mocha-webdriver - was built for saucelabs which I don't care about and seems to ONLY run against phantomjs

https://github.com/christian-bromann/grunt-webdriver - is great and runs against many browsers including phantomjs, but doesn't appear to support mocha style tests.

**Comment by wookiehangover** [comment]
Good suggestion! Looks like @drd's pull request should wrap this up nicely...
