### ISSUE TITLE
unable to install grunt-mocha-selenium.

### ISSUE THREAD

**Issue by kavish28** [wookiehangover/grunt-mocha-selenium#18]
I am trying to install npm install grunt-mocha-selenium
I see following error:
 silly lockFile 7fd70be4-ver-nodejs-selenium-launcher-git git://github.com/wookiehangover/nodejs-selenium-launcher.git
159 verbose about to build /xxx/npm/node_modules/grunt-mocha-selenium
160 info /xxx/npm/node_modules/grunt-mocha-selenium unbuild
161 info preuninstall grunt-mocha-selenium@0.7.0
162 info uninstall grunt-mocha-selenium@0.7.0
163 verbose true,/xxx/npm/node_modules,/home/ksharda/npm/node_modules unbuild grunt-mocha-selenium@0.7.0
164 info postuninstall grunt-mocha-selenium@0.7.0
165 error not found: git
166 error Failed using git.
166 error This is most likely not a problem with npm itself.
166 error Please check if you have git installed and in your PATH.
167 error System Linux 3.5.0-17-generic
168 error command "/usr/bin/node" "/usr/bin/npm" "install" "grunt-mocha-selenium"
169 error cwd /xxx/npm/node_modules
170 error node -v v0.10.26
171 error npm -v 1.4.3
172 error code ENOGIT
173 verbose exit [ 1, true ]

any idea why?

**Comment by kavish28** [comment]
okay. looks like in packaga.json there is dependency for  "selenium-launcher": "git://github.com/wookiehangover/nodejs-selenium-launcher.git",
this requires to download git. 
do we need this dependency, ?

**Comment by kavish28** [comment]
m WARN `git config --get remote.origin.url` returned wrong result (git://github.com/wookiehangover/nodejs-selenium-launcher.git)
npm http 304 https://registry.npmjs.org/freeport
npm http 304 https://registry.npmjs.org/phantomjs
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/wd
npm ERR! git clone git://github.com/wookiehangover/nodejs-selenium-launcher.git Cloning into bare repository '/home/ksharda/.npm/_git-remotes/git-github-com-wookiehangover-nodejs-selenium-launcher-git-7fd70be4'...
npm ERR! git clone git://github.com/wookiehangover/nodejs-selenium-launcher.git
npm ERR! git clone git://github.com/wookiehangover/nodejs-selenium-launcher.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/wookiehangover/nodejs-selenium-launcher.git github.com[0: 192.30.252.131]: errno=Connection timed out
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=Connection timed out

Can someone please help?

**Comment by nicovalencia** [comment]
Yes, the launcher is a required dependency. This is an issue with your connection to GitHub. I'd check your internet connection, and try again.

**Comment by kavish28** [comment]
I am sure its not internet connection.because I am able to ping to github.com directlt and I was able to download other packages from github. Not sure whats wrong with it. I will try again.

**Comment by wookiehangover** [comment]
Sorry about this, guys. I need to rename my fork of nodejs-selenium-launcher and publish it to npm.
